# Saving a  Model
After training a model to perform a particular function, we save it. so incase we want to reuse the model to answer some questions we don't need to retrain the model again. We do this using python's pickle model and Joblib.

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv(r"C:\Users\Anotijakes\Documents\DATAS\CSV DATA\homepri.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000
5  4100  810000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [4]:
model.coef_

array([167.30954677])

In [5]:
model.intercept_

76692.3818707813

In [6]:
model.predict([[5000]])

C:\Users\Anotijakes\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

So now we can save the model in a file using pickle or joblib
using pickle we do:

In [7]:
#using pickle

import pickle

In [8]:
with open ('model_pickel', 'wb') as f:
    pickle.dump(model, f)

In [9]:
with open ('model_pickel', 'rb') as f:
    mb = pickle.load(f)

In [13]:
#lets still trial out predicting the price of 5000 area

mb.predict([[5000]])

C:\Users\Anotijakes\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

In [15]:
#to use joblib to save models we would need to import it from sklearn
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\Anotijakes\anaconda3\lib\site-packages\sklearn\externals\__init__.py)